version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./tests/unmocked_unit_tests.py
          name: app.py Tests
      

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
     